name: rl-protect scan
on:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: tpericin/gh-action-rl-protect-scan@sdlc-comment
        env:
          RL_TOKEN: ${{ secrets.RL_TOKEN }}
        with:
          scan-path: requirements.txt
          report: rl-protect-pip.report.json
          post-pr-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-template: 'concise'
      - uses: tpericin/gh-action-rl-protect-scan@sdlc-comment
        if: always()
        env:
          RL_TOKEN: ${{ secrets.RL_TOKEN }}
        with:
          scan-path: projects/package.json
          scan-profile: .rl-protect/custom-profile.json
          check-deps: release,transitive
          report: rl-protect-npm-1.report.json
          post-pr-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-template: 'expanded'
